### ISSUE TITLE
Enable HTML and JS in Markdown

### ISSUE THREAD

**Issue by thebootroo** [OneMoreGres/qtc-markview#1]
It can be useful to keep inline HTML and JS in the Markdown conversion, we can use this to do things not supported by Markdown by default like Table Of Content.

But the sanitize option enabled disables HTML and JavaScript, and even with it disabled and plugin rebuild, HTML works but not JavaScript....

**Comment by OneMoreGres** [comment]
Hi.
Inline scripts (`<p onclick=alert('qwe')>`) work with `sanitize` disabled.
`<script>` tags are escaped in cpp code because otherwise they break plugins conversion scripts.
For now i know neither how to correctly pass them to the document nor should it be done at all since it's a markdown editor and web functionality is just an implementations side effect.
Any tips are welcome, preferably with code or pull request :)

**Comment by thebootroo** [comment]
Yeah, very simple scripts work, mine was more complicated, to generate TOC, and even inlined, it doesn't work...

So my next suggestions : 

1 - please  make the "sanitize" flag (and maybe some more) configurable in Qt Creator options
2 - why not support TOC extension to Markdown (very demanded feature and widely found on the web)
3 - else, provide a way to attach CSS and JavaScript files to the viewer, via QtCreator options

This way one can use whatever we want to add custom style and/or behavior to the Markdown viewer.

**Comment by OneMoreGres** [comment]
Not exactly what you meant, but..
Now you can add and remove your own conversion scripts with any js/css included. There are buttons for it in editor, near help button. Try it.
[test.zip](https://github.com/OneMoreGres/qtc-markview/files/709254/test.zip)

**Comment by thebootroo** [comment]
I tried, not that far from what I need actually. 

I've been able to reconfigure marked.js and add custom JS for table of contents, and some custom CSS rules.

**Comment by OneMoreGres** [comment]
This is linux binary corresponding to current master branch, if you need it. Fixed some bugs from test.zip.
[libQtcMarkview.zip](https://github.com/OneMoreGres/qtc-markview/files/712057/libQtcMarkview.zip)
