### ISSUE TITLE
Not working with newest QtCreator 4.7.0

### ISSUE THREAD

**Issue by jaques-sam** [OneMoreGres/qtc-markview#3]
This seems like a very nice plugin, unfortunately it's not working for the latest QtCreator version:
```
Could not resolve dependency 'Core(4.3.0)'
Could not resolve dependency 'TextEditor(4.3.0)'
```
I installed it as usual by extracting all files into the QtCreator folder.

**Comment by OneMoreGres** [comment]
What version of plugin/OS do you use? Plugin's version must match Qt Creator's version (except semver's patch version).

**Comment by jaques-sam** [comment]
Latest version from the link on the README (https://sourceforge.net/projects/qtc-markview/files/) is 4.3.1.
So this means there are no plugins available since QtCreator 4.4? Can you make a new release tag and test?
Thank you!

**Comment by OneMoreGres** [comment]
Updated readme. Rescent plugin versions can be found on [releases page](https://github.com/OneMoreGres/qtc-markview/releases)

**Comment by VidhyaCeleber** [comment]
Tested this plugin with 4.11 and I get dependency errors with Core and Text Editor. 
Does this plugin work for ascii documents as well ?
I am trying to build and test this plugin with various versions but unfortunately nothing seems to be successful. Tested with code and binary versions too, nothing helped.

Can you please support ?

**Comment by OneMoreGres** [comment]
I link it with the Qtc's binaries from [here](https://download.qt.io/).
I take the sources from there too.
The version of the plugin indicates the the Qtc's version it was linked with.
So, the precompiled binaries must work with the same Qtc's version (depending on the Qtc's binary compatibility it may also support different patch versions).

Starting from some version the behavior of the plugin has changed.
It no longer provides a formatted view split (like in the screenshot in readme).
It just highlights (color and size) some text elements and only supports markdown.
So maybe it works, just not as expected.

Generic ascii documents are supported too.
In this case it acts just like a regular editor.

You can open any document in this editor via "open with" context menu of the file selector's combobox (top left corner of each editor).

I'll update the readme with an actual screenshot so as not to be misleading.

**Comment by VidhyaCeleber** [comment]
I tried taking the binaries from https://github.com/OneMoreGres/qtc-markview/releases
and linked it with my Qt creator 4.11 version. Alternatively, I also tried taking your plugin source and i built it myself with Qt creator 4.11.

Can you please confirm with which version its expected to work fine ? I can try with the same version and get back. Meanwhile, the link you have sent above belongs to which version of qt creator.. I couldn't find that . Thank you for the support.

**Comment by OneMoreGres** [comment]
Plugin 4.11.0 works with Qt Creator 4.11.0 installed by online installer or from [here](https://download.qt.io/official_releases/qtcreator/4.11/4.11.0/). Just extract/copy contents to Qt Creator's directory and enable plugin in settings.
Similarly, plugin 4.10.0 works with Qt Creator 4.10.0, plugin 4.9 - with Qt Creator 4.9 and so on.

By posting a link to `download.qt.io` I wanted to say that precompiled versions works only with Qt Creator versions downloaded from there, but not from debian/chocolatey/homebrew repositories.
