### ISSUE TITLE
Does not work with QtCreator 4.9.0/4.9.2

### ISSUE THREAD

**Issue by d8vLoper** [OneMoreGres/qtc-markview#4]
I just installed the last version from https://github.com/OneMoreGres/qtc-markview/releases wich is 4.9.0.
Files added :
- QtcMarkview4.dll in _Tools\QtCreator\lib\qtcreator\plugins_ folder
- QtcMarkview_ru.qm in _Tools\QtCreator\share\qtcreator\translations_ folder

When i enable the plugin and restart QtCreator, I have the following error at launch :
![error](https://user-images.githubusercontent.com/47775376/64237436-a3ff2a80-cefc-11e9-8b33-04db429b5234.png)
which means _C:\Qt\Tools\QtCreator\lib\qtcreator\plugins\QtcMarkview4.dll : can't load library_

Tested with QtCreator 4.90 and 4.9.2.

**Comment by OneMoreGres** [comment]
What version of Qt Creator do you use? Was it downloaded from "download.qt.io" of somewhere else?
And does this issue still actual after 4.10 release?

**Comment by d8vLoper** [comment]
I use the Qt Maintenance Tool to update QtCreator.
I've just updated to 4.10 and I have a different error (version mismatch) : https://user-images.githubusercontent.com/47775376/64512159-10f03700-d2e6-11e9-84af-1a888da1aead.png

**Comment by OneMoreGres** [comment]
Update the plugin too (https://github.com/OneMoreGres/qtc-markview/releases/tag/4.10.0)

**Comment by d8vLoper** [comment]
Works ok in 4.10 !

**Comment by OneMoreGres** [comment]
Nice to hear. Closing the issue then.
