### ISSUE TITLE
Not able to view ascii docs

### ISSUE THREAD

**Issue by VidhyaCeleber** [OneMoreGres/qtc-markview#5]
I have built this code successfully and the library libQtcMarkview.so is also generated. I find this plugin enabled in Settings as well.

But I am not sure how to execute it. I have created a new ascii file in my qtcreator editor and shifted to split view. From your screenshot i see, there should be an option in the top editor where markdown / ascii should be listed. I dont find any such option getting listed other than Unix(LF)/Windows(CRLF) in drop down. Kindly guide on how to view this.

One observation:

When I open an *.md file, i find the markdown file with proper updates. So is it only a viewer plugin which can view markdown files or i can edit and view them too ?
Similarly does it support ascii docs as well ? I tried opening an adoc file but i could not view it as an ascii content.

**Comment by VidhyaCeleber** [comment]
I have built this code successfully and the library libQtcMarkview.so is also generated. I find this plugin enabled in Settings as well.

But I am not sure how to execute it. I have created a new ascii file in my qtcreator editor and shifted to split view. From your screenshot i see, there should be an option in the top editor where markdown / ascii should be listed. I dont find any such option getting listed other than Unix(LF)/Windows(CRLF) in drop down. Kindly guide on how to view this.

I have created a new issue also as just found this one to be in closed state.

**Comment by OneMoreGres** [comment]
As I said [earlier](https://github.com/OneMoreGres/qtc-markview/issues/3#issuecomment-589217366), starting from some version the behavior of the plugin has changed. It no longer provides a formatted view split. It just highlights (color and size) some text elements and only supports markdown.

So, yes, it only supports markdown (as mentioned in the readme).
You can both view and edit opened document.
I updated the screenshot in the readme so it no longer contains outdated format switch.
It may support some subset of asciidoc (btw ascii document not exactly the same as asciidoc document), but that's likely will not be enough. This editor can be manually selected for any textual document via this menu
![image](https://user-images.githubusercontent.com/3948993/75174498-ba66a000-5741-11ea-8b6f-4565d8d5808a.png)
