### ISSUE TITLE
Can't write when autocomplete popup is opened

### ISSUE THREAD

**Issue by jesustorresdev** [OneMoreGres/qtc-markview#7]
If I'm writing and the autocomplete popup is opened, I can't write until I close the popup.

**Comment by OneMoreGres** [comment]
Which version (win64/win32/..) do you use, so I can put it here until the next release?

**Comment by jesustorresdev** [comment]
4.12 win32 and linux.

**Comment by OneMoreGres** [comment]
From CI
[QtcMarkview-4.12.0-linux.tar.gz.zip](https://github.com/OneMoreGres/qtc-markview/files/4564189/QtcMarkview-4.12.0-linux.tar.gz.zip)
[QtcMarkview-4.12.0-win32.zip.zip](https://github.com/OneMoreGres/qtc-markview/files/4564190/QtcMarkview-4.12.0-win32.zip.zip)

**Comment by jesustorresdev** [comment]
Thank you very much.
Works fine.
