### ISSUE TITLE
links to gres.biz

### ISSUE THREAD

**Issue by esaulenka** [OneMoreGres/qtc-markview#8]
Links to [gres.biz](gres.biz) in readme.md and [wiki.qt.io](wiki.qt.io/Qt_Creator_Plug-in_Gallery) are broken.

**Comment by OneMoreGres** [comment]
Wiki's changes are on moderation. I don't know if/when they'll be accepted/rejected

**Comment by esaulenka** [comment]
Спасибо!
Мёртвые ссылки создавали ощущение "заброшенности".
